/**
 * Static catalog for Admin bilingual settings search.
 * Add a row here (+ data-setting-key on the field) when introducing new searchable settings.
 */

export type AdminSearchEntry = {
  id: string;
  kind: 'tab' | 'setting';
  /** Main Admin tab id (ADMIN_TABS) */
  tab: string;
  /** Full location hash, e.g. #admin#system-settings#mail-server or #admin#project-settings#lifecycle */
  hash: string;
  /** Scroll target: [data-setting-key="…"] */
  settingKey?: string;
  /** i18next key under the `admin` namespace */
  labelKey: string;
  /** Extra EN/FR tokens (smtp, oauth, llm, …) */
  aliases?: string[];
  /** Additional admin i18n keys included in the search haystack (EN+FR). */
  extraLabelKeys?: string[];
};

export const ADMIN_SEARCH_INDEX: AdminSearchEntry[] = [
  // —— Tabs ——
  {
    id: 'tab-users',
    kind: 'tab',
    tab: 'users',
    hash: '#admin#users',
    labelKey: 'tabs.users',
    aliases: ['utilisateurs', 'user', 'members', 'membres'],
  },
  {
    id: 'tab-site-settings',
    kind: 'tab',
    tab: 'site-settings',
    hash: '#admin#site-settings',
    labelKey: 'tabs.siteSettings',
    aliases: ['branding', 'logo', 'site'],
  },
  {
    id: 'tab-system-settings',
    kind: 'tab',
    tab: 'system-settings',
    hash: '#admin#system-settings#sso',
    labelKey: 'tabs.systemSettings',
    aliases: ['system', 'système', 'systeme', 'infrastructure'],
  },
  {
    id: 'tab-sso',
    kind: 'tab',
    tab: 'system-settings',
    hash: '#admin#system-settings#sso',
    labelKey: 'tabs.sso',
    aliases: ['oauth', 'google', 'connexion', 'login'],
  },
  {
    id: 'tab-mail',
    kind: 'tab',
    tab: 'system-settings',
    hash: '#admin#system-settings#mail-server',
    labelKey: 'tabs.mailServer',
    aliases: ['smtp', 'email', 'courriel', 'mail', 'messagerie'],
  },
  {
    id: 'tab-storage',
    kind: 'tab',
    tab: 'system-settings',
    hash: '#admin#system-settings#storage',
    labelKey: 'tabs.storage',
    aliases: ['s3', 'bucket', 'attachments', 'avatars', 'nfs', 'object storage', 'stockage'],
  },
  {
    id: 'tab-file-uploads',
    kind: 'tab',
    tab: 'system-settings',
    hash: '#admin#system-settings#file-uploads',
    labelKey: 'appSettings.fileUploads',
    aliases: ['upload', 'fichiers', 'attachments', 'pièces jointes', 'mime'],
  },
  {
    id: 'tab-ai',
    kind: 'tab',
    tab: 'system-settings',
    hash: '#admin#system-settings#ai',
    labelKey: 'appSettings.ai',
    aliases: ['ai', 'ia', 'agent', 'llm', 'openai', 'anthropic'],
  },
  {
    id: 'tab-notifications',
    kind: 'tab',
    tab: 'system-settings',
    hash: '#admin#system-settings#notifications',
    labelKey: 'appSettings.notifications',
    aliases: ['notification', 'email alerts', 'alertes'],
  },
  {
    id: 'tab-webhooks',
    kind: 'tab',
    tab: 'system-settings',
    hash: '#admin#system-settings#webhooks',
    labelKey: 'webhooks.tabLabel',
    aliases: [
      'webhook',
      'slack',
      'teams',
      'telegram',
      'whatsapp',
      'mattermost',
      'delivery channel',
      'canal',
      'outgoing',
    ],
  },
  {
    id: 'tab-notification-queue',
    kind: 'tab',
    tab: 'system-settings',
    hash: '#admin#system-settings#notification-queue',
    labelKey: 'tabs.notificationQueue',
    aliases: ['queue', 'file', 'pending emails', 'e-mails en attente'],
  },
  {
    id: 'tab-tags',
    kind: 'tab',
    tab: 'tags',
    hash: '#admin#tags',
    labelKey: 'tabs.tags',
    aliases: ['étiquettes', 'etiquettes', 'labels'],
  },
  {
    id: 'tab-priorities',
    kind: 'tab',
    tab: 'priorities',
    hash: '#admin#priorities',
    labelKey: 'tabs.priorities',
    aliases: ['priorités', 'priorites'],
  },
  {
    id: 'tab-app-settings',
    kind: 'tab',
    tab: 'app-settings',
    hash: '#admin#app-settings#user-interface',
    labelKey: 'tabs.appSettings',
    aliases: ['application', 'ui', 'interface'],
  },
  {
    id: 'tab-project-settings',
    kind: 'tab',
    tab: 'project-settings',
    hash: '#admin#project-settings#project',
    labelKey: 'tabs.projectSettings',
    aliases: ['projet', 'project'],
  },
  {
    id: 'tab-features',
    kind: 'tab',
    tab: 'project-settings',
    hash: '#admin#project-settings#features',
    labelKey: 'projectHub.featuresSubtab',
    aliases: ['features', 'fonctions', 'wip', 'effort', 'counts', 'visibilité', 'visibility', 'overdue', 'retard', 'hours', 'points'],
  },
  {
    id: 'tab-sprint-settings',
    kind: 'tab',
    tab: 'project-settings',
    hash: '#admin#project-settings#sprint-settings',
    labelKey: 'tabs.sprintSettings',
    aliases: ['sprint', 'agile'],
  },
  {
    id: 'tab-reporting',
    kind: 'tab',
    tab: 'project-settings',
    hash: '#admin#project-settings#reporting',
    labelKey: 'tabs.reporting',
    aliases: ['rapports', 'reports', 'analytics'],
  },
  {
    id: 'tab-lifecycle',
    kind: 'tab',
    tab: 'project-settings',
    hash: '#admin#project-settings#lifecycle',
    labelKey: 'tabs.lifecycle',
    aliases: ['cycle de vie', 'retention', 'rétention', 'trash', 'corbeille', 'purge'],
  },
  {
    id: 'tab-licensing',
    kind: 'tab',
    tab: 'licensing',
    hash: '#admin#licensing',
    labelKey: 'tabs.licensing',
    aliases: ['licence', 'license', 'subscription', 'abonnement'],
  },

  // —— Site settings ——
  {
    id: 'site-name',
    kind: 'setting',
    tab: 'site-settings',
    hash: '#admin#site-settings',
    settingKey: 'SITE_NAME',
    labelKey: 'siteSettings.siteName',
    aliases: ['nom du site', 'title', 'titre'],
  },
  {
    id: 'site-url',
    kind: 'setting',
    tab: 'site-settings',
    hash: '#admin#site-settings',
    settingKey: 'SITE_URL',
    labelKey: 'siteSettings.siteUrl',
    aliases: ['url'],
  },
  {
    id: 'site-logo',
    kind: 'setting',
    tab: 'site-settings',
    hash: '#admin#site-settings',
    settingKey: 'SITE_LOGO',
    labelKey: 'siteSettings.siteLogo',
    aliases: ['logo', 'branding', 'image'],
  },
  {
    id: 'site-logo-dark',
    kind: 'setting',
    tab: 'site-settings',
    hash: '#admin#site-settings',
    settingKey: 'SITE_LOGO_DARK',
    labelKey: 'siteSettings.siteLogoDark',
    aliases: ['logo dark', 'logo sombre'],
  },

  // —— SSO (System Settings) ——
  {
    id: 'google-client-id',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#sso',
    settingKey: 'GOOGLE_CLIENT_ID',
    labelKey: 'sso.googleClientId',
    aliases: ['oauth', 'google', 'client id'],
  },
  {
    id: 'google-client-secret',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#sso',
    settingKey: 'GOOGLE_CLIENT_SECRET',
    labelKey: 'sso.googleClientSecret',
    aliases: ['oauth', 'google', 'secret', 'secret client'],
  },
  {
    id: 'google-callback',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#sso',
    settingKey: 'GOOGLE_CALLBACK_URL',
    labelKey: 'sso.googleCallbackUrl',
    aliases: ['callback', 'redirect', 'oauth'],
  },

  // —— Mail (System Settings) ——
  {
    id: 'smtp-host',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#mail-server',
    settingKey: 'SMTP_HOST',
    labelKey: 'mail.smtpHost',
    aliases: ['smtp', 'host', 'serveur'],
  },
  {
    id: 'smtp-port',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#mail-server',
    settingKey: 'SMTP_PORT',
    labelKey: 'mail.smtpPort',
    aliases: ['smtp', 'port'],
  },
  {
    id: 'smtp-username',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#mail-server',
    settingKey: 'SMTP_USERNAME',
    labelKey: 'mail.smtpUsername',
    aliases: ['smtp', 'username', 'utilisateur'],
  },
  {
    id: 'smtp-password',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#mail-server',
    settingKey: 'SMTP_PASSWORD',
    labelKey: 'mail.smtpPassword',
    aliases: ['smtp', 'password', 'mot de passe', 'mdp'],
  },
  {
    id: 'smtp-from-email',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#mail-server',
    settingKey: 'SMTP_FROM_EMAIL',
    labelKey: 'mail.fromEmail',
    aliases: ['from', 'expéditeur', 'expediteur', 'sender'],
  },
  {
    id: 'smtp-from-name',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#mail-server',
    settingKey: 'SMTP_FROM_NAME',
    labelKey: 'mail.fromName',
    aliases: ['from name', 'nom expéditeur'],
  },
  {
    id: 'smtp-secure',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#mail-server',
    settingKey: 'SMTP_SECURE',
    labelKey: 'mail.smtpSecurity',
    aliases: ['tls', 'ssl', 'security', 'sécurité'],
  },

  // —— AI (System Settings) ——
  {
    id: 'ai-section',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#ai',
    settingKey: 'AI_ENABLED',
    labelKey: 'appSettings.aiEnabled',
    aliases: ['ai', 'ia', 'agent', 'llm', 'openai', 'anthropic'],
  },
  {
    id: 'ai-provider',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#ai',
    settingKey: 'AI_PROVIDER',
    labelKey: 'appSettings.aiProvider',
    aliases: ['provider', 'fournisseur', 'openai', 'anthropic', 'ollama', 'openrouter'],
  },
  {
    id: 'ai-api-key',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#ai',
    settingKey: 'AI_API_KEY',
    labelKey: 'appSettings.aiApiKey',
    aliases: ['api key', 'clé api', 'cle api', 'token', 'secret'],
  },
  {
    id: 'ai-model',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#ai',
    settingKey: 'AI_MODEL',
    labelKey: 'appSettings.aiModel',
    aliases: ['model', 'modèle', 'modele', 'gpt', 'claude'],
  },
  {
    id: 'ai-base-url',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#ai',
    settingKey: 'AI_API_BASE_URL',
    labelKey: 'appSettings.aiApiBaseUrl',
    aliases: ['base url', 'endpoint', 'url'],
  },
  {
    id: 'ai-runner-url',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#ai',
    settingKey: 'AI_RUNNER_URL',
    labelKey: 'appSettings.aiRunnerUrl',
    aliases: ['runner', 'agent runner'],
  },
  {
    id: 'ai-runner-token',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#ai',
    settingKey: 'AI_RUNNER_TOKEN',
    labelKey: 'appSettings.aiRunnerToken',
    aliases: ['runner token', 'jeton runner'],
  },
  {
    id: 'ai-max-concurrent',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#ai',
    settingKey: 'AI_MAX_CONCURRENT',
    labelKey: 'appSettings.aiMaxConcurrent',
    aliases: ['concurrent', 'simultané', 'limite', 'parallel'],
  },

  // —— Troubleshooting ——
  {
    id: 'troubleshooting',
    kind: 'setting',
    tab: 'app-settings',
    hash: '#admin#app-settings#troubleshooting',
    settingKey: 'TROUBLESHOOTING_SECTION',
    labelKey: 'appSettings.troubleshooting',
    aliases: ['debug', 'logs', 'débogage', 'debogage', 'fe_debug', 'server_debug'],
  },
  {
    id: 'allow-user-self-delete',
    kind: 'setting',
    tab: 'app-settings',
    hash: '#admin#app-settings#user-interface',
    settingKey: 'ALLOW_USER_SELF_DELETE',
    labelKey: 'appSettings.allowUserSelfDelete',
    aliases: ['self delete', 'delete account', 'supprimer compte', 'offboarding'],
  },

  // —— File uploads (System Settings) ——
  {
    id: 'file-uploads',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#file-uploads',
    settingKey: 'UPLOADS_SECTION',
    labelKey: 'appSettings.fileUploads',
    aliases: ['upload', 'fichiers', 'attachments', 'pièces jointes'],
  },

  // —— Notifications (System Settings) ——
  {
    id: 'notifications',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#notifications',
    settingKey: 'NOTIFICATIONS_SECTION',
    labelKey: 'appSettings.notifications',
    aliases: ['notification', 'email alerts', 'alertes'],
  },
  {
    id: 'webhook-delivery-channel',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#webhooks',
    settingKey: 'TASK_NOTIFICATION_CHANNELS',
    labelKey: 'webhooks.channelModeTitle',
    extraLabelKeys: [
      'webhooks.channelModeHint',
      'webhooks.channel.email',
      'webhooks.channel.both',
      'webhooks.channel.webhooks',
      'webhooks.channelHelp.email',
      'webhooks.channelHelp.both',
      'webhooks.channelHelp.webhooks',
    ],
    aliases: ['delivery channel', 'canal', 'TASK_NOTIFICATION_CHANNELS'],
  },
  {
    id: 'webhook-list',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#webhooks',
    settingKey: 'WEBHOOKS_LIST',
    labelKey: 'webhooks.listTitle',
    aliases: [
      'outgoing webhook',
      'incoming webhook url',
      'endpoint',
      'slack',
      'mattermost',
      'teams',
      'telegram',
      'whatsapp',
    ],
  },
  {
    id: 'webhook-event-types',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#webhooks',
    settingKey: 'WEBHOOK_EVENT_TYPES',
    labelKey: 'webhooks.eventTypes',
    extraLabelKeys: [
      'webhooks.eventTypesHint',
      'webhooks.events.taskCreated',
      'webhooks.events.taskChanged',
      'webhooks.events.taskDeleted',
      'webhooks.events.boardCreated',
      'webhooks.events.boardRenamed',
      'webhooks.events.boardDeleted',
    ],
    aliases: ['event types', 'types d evenements'],
  },
  {
    id: 'notification-queue-retention',
    kind: 'setting',
    tab: 'system-settings',
    hash: '#admin#system-settings#notification-queue',
    settingKey: 'NOTIFICATION_QUEUE_RETENTION_DAYS',
    labelKey: 'notificationQueue.retentionDays',
    aliases: ['retention', 'rétention', 'purge', 'queue cleanup', 'nettoyage file'],
  },

  // —— Lifecycle (Project Settings) ——
  {
    id: 'lifecycle-retention',
    kind: 'setting',
    tab: 'project-settings',
    hash: '#admin#project-settings#lifecycle',
    settingKey: 'LIFECYCLE_DELETED_RETENTION_DAYS',
    labelKey: 'lifecycle.deletedRetention',
    aliases: ['retention', 'rétention', 'purge', 'soft delete', 'suppression récupérable'],
  },
  {
    id: 'lifecycle-archived',
    kind: 'setting',
    tab: 'project-settings',
    hash: '#admin#project-settings#lifecycle',
    settingKey: 'LIFECYCLE_ARCHIVED_RETENTION_DAYS',
    labelKey: 'lifecycle.archivedRetention',
    aliases: ['archive', 'archivé', 'retention'],
  },
];
